# Generated by Django 4.2.1 on 2025-06-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrating',
            options={'ordering': ['-points'], 'verbose_name': 'Рейтинг пользователя', 'verbose_name_plural': 'Рейтинги пользователей'},
        ),
        migrations.AddField(
            model_name='userrating',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
