# Generated by Django 4.2.1 on 2025-05-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mero_on_site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(max_length=255)),
                ('volunteering', models.BooleanField(default=False)),
            ],
        ),
    ]
