# Generated by Django 4.2.1 on 2025-05-13 21:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mero', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mero_on_site',
            options={'ordering': ['-time'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AddField(
            model_name='mero_on_site',
            name='photo',
            field=models.ImageField(blank=True, help_text='Загрузите фотографию для мероприятия', null=True, upload_to='events/photos/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='mero_on_site',
            name='description',
            field=models.TextField(blank=True, help_text='Подробное описание мероприятия', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mero_on_site',
            name='event_type',
            field=models.CharField(choices=[('CANC', 'Концерт'), ('KYRS', 'Курс'), ('VST', 'Выставка'), ('DAY', 'День открытых дверей'), ('WORK', 'Мастер-класс'), ('CONKYR', 'Конкурс'), ('SPEK', 'Спектакль'), ('SPORT', 'Спорт'), ('CONF', 'Конгресс'), ('FORUM', 'Форум')], default='OTHER', max_length=7, verbose_name='Тип мероприятия'),
        ),
        migrations.AlterField(
            model_name='mero_on_site',
            name='name',
            field=models.CharField(help_text='Введите название мероприятия', max_length=200, verbose_name='Название мероприятия'),
        ),
        migrations.AlterField(
            model_name='mero_on_site',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Укажите дату и время начала', verbose_name='Время проведения'),
        ),
        migrations.AlterField(
            model_name='mero_on_site',
            name='volunteering',
            field=models.BooleanField(default=False, help_text='Отметьте, если нужны волонтеры', verbose_name='Требуются волонтеры'),
        ),
    ]
