# Generated by Django 4.2.1 on 2025-05-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mero', '0003_alter_mero_on_site_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mero_on_site',
            name='event_type',
            field=models.CharField(choices=[('CONC', 'Концерт'), ('KYRC', 'Курс'), ('VST', 'Выставка'), ('DAY', 'День открытых дверей'), ('MAST', 'Мастер-класс'), ('KONK', 'Конкурс'), ('SPEK', 'Спектакль'), ('SPORT', 'Спорт'), ('CONGR', 'Конгресс'), ('FORUM', 'Форум')], default='OTHER', max_length=10, verbose_name='Тип мероприятия'),
        ),
    ]
