# Generated by Django 4.2.1 on 2025-05-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mero', '0004_alter_mero_on_site_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mero_on_site',
            name='event_type',
            field=models.CharField(choices=[('Концерт', 'Концерт'), ('Курс', 'Курс'), ('Выставка', 'Выставка'), ('День открытых дверей', 'День открытых дверей'), ('Мастер-класс', 'Мастер-класс'), ('Конкурс', 'Конкурс'), ('Спектакль', 'Спектакль'), ('Спорт', 'Спорт'), ('Конгресс', 'Конгресс'), ('Форум', 'Форум')], default='OTHER', max_length=20, verbose_name='Тип мероприятия'),
        ),
    ]
