# Generated by Django 4.2.1 on 2025-06-09 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mero', '0005_alter_mero_on_site_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mero_on_site',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
