# Generated by Django 4.2.1 on 2025-06-17 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mero', '0006_mero_on_site_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='mero_on_site',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='volunteer_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
